version: '3.9'

services:
  service-db:
    image: postgres:14.8-alpine3.18
    container_name: costs_db
    environment:
      POSTGRES_USER: "u_admin"
      POSTGRES_PASSWORD: "adminpass"
      POSTGRES_DB: "db_costs"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - costs-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service-app:
    build: 
      context: cost-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/db_costs
    container_name: costs_app
    depends_on:
      - service-db
    ports:
      - '8080:8080'
volumes:
  costs-data: