version: '3.9'

services:
  service-db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: "u_admin"
      POSTGRES_PASSWORD: "adminpass"
      POSTGRES_DB: "db_costs"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - costs-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  costs-data: