@startsalt categories
{
    {SI
        Транспорт | 1499.05
        Хозтовары | 147.50
        Питание   | 99.99
        .
    }
    {
       Дата с | "01.02.2024"
       Дата по | "15.02.2024"
       [Просмотреть] | [ Вернуться ]
    }
}
@endsalt