@startsalt cost
{
  Дата      | "01.01.2024            "
  Расход    | "Наименование расхода  "
  Категория | ^Категория расходов^
  Сумма     | "999.99                "
  [Сохранить] | [ Отмена  ]
}
@endsalt