@startsalt cost
{
  Дата      | "01.01.2024            "
  Расход    | "Наименование расхода  "
  Категория | ^Категория расходов^ Питание^ Транспорт^ Хозтовары^ Здоровье^
  .
  .
  .
  .
  Счёт      | ^Счёт              ^ Наличные^ Карта^ Банковский счёт^
  .
  .
  .
  Сумма     | "999.99                "
  [Сохранить] | [ Отмена  ]
}
@endsalt