@startsalt costs
{
    {SI
        Бензин | Транспорт | 1499.05
        Зубная щетка | Хозтовары | 147.50
        Молоко | Питание | 99.99
        Огурцы | Питание | 255.00
        Туалетная бумага | Хозтовары | 10.99
        .
    }
    {
        [Создать] | [Просмотр по категориям]
    }
}
@endsalt