@startsalt costs
{
    {SI
        03.02.2024 | Бензин | Транспорт | 1499.05
        01.02.2024 | Зубная щетка | Хозтовары | 147.50
        01.02.2024 | Молоко | Питание | 99.99
        31.01.2024 | Огурцы | Питание | 255.00
        30.01.2024 | Туалетная бумага | Хозтовары | 10.99
        .
    }
    {
        [Создать] | [Просмотр по категориям]
    }
}
@endsalt