@startuml main
:Админ: as Admin

(Вход в приложение) as (Login)
(Список пользователей) as (Users)
(Список расходов) as (Costs)
(Карточка пользователя) as (User)
(Карточка расхода) as (Cost)
(Расходы по категориям) as (Categories)

Пользователь --> (Login)

Admin ---> (Login)

Login ---> (Users) : Если пароль верный\nи роль ADMIN
Login ---> (Costs) : Если пароль верный\nи роль USER
Login ---> (Login) : Если пароль неверный

Users ---> (User) : Создать\nнового\nпользователя
Users ---> (User) : Изменить\nсуществующего\nпользователя

Costs ---> (Cost) : Создать\nновый\nрасход
Costs ---> (Cost) : Изменить\nсуществующий\nрасход

User ---> (Users) : Сохранить\nпользователя
User ---> (Users) : Удалить\nпользователя
User ---> (Users) : Вернуться\nбез сохранения

Cost ---> (Costs) : Сохранить\nрасход
Cost ---> (Costs) : Удалить\nрасход
Cost ---> (Costs) : Вернуться\nбез сохранения

Costs ---> (Categories) : Перейти (по умолчанию\nпериод: текущий месяц)
Categories ---> (Categories) : Просмотреть расходы за выбранный период
Categories ---> (Costs) : Вернуться

note left of Login : Далее переход в зависимости от роли

@enduml